name: CI for Laravel 11 and Your Package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup PHP ğŸ˜
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql
          tools: composer:v2

      - name: Install Laravel 11 ğŸ› ï¸
        run: |
          composer create-project --prefer-dist laravel/laravel laravel-app "11.*"
        
      - name: Navigate to Laravel Project ğŸ“‚
        run: cd laravel-app

      - name: Install try-on ğŸ“¦
        run: |
          composer require caraxes/try-on
          
      - name: Install Dependencies ğŸ“¦
        run: |
          cd laravel-app && composer install --prefer-dist --no-progress --no-suggest --dev

      - name: Optimize Laravel ğŸ› ï¸
        run: |
          cd laravel-app && php artisan config:cache
          cd laravel-app && php artisan optimize

      # - name: Run Migrations ğŸ—‚ï¸
      #   run: |
      #     cd laravel-app && php artisan migrate --env=testing

      # - name: Run Tests âœ…
      #   run: |
      #     cd laravel-app && vendor/bin/phpunit --testdox

      # - name: Run Static Analysis ğŸ”
      #   run: |
      #     cd laravel-app && vendor/bin/phpstan analyse app/ --level=5
