name: CI for Laravel 11 and Your Package

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup PHP ğŸ˜
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, pdo, pdo_mysql
          tools: composer:v2, phpunit, phpstan

      - name: Install Laravel 11 ğŸ› ï¸
        run: composer create-project --prefer-dist laravel/laravel laravel-app "11.*"

      - name: Install try-on Package ğŸ“¦
        run: |
          cd laravel-app
          composer config repositories.try-on path ../
          composer require caraxes/try-on:dev-main

      - name: Install Dependencies ğŸ“¦
        run: cd laravel-app && composer install --prefer-dist --no-progress --no-suggest --dev

      - name: Optimize Laravel ğŸ› ï¸
        run: cd laravel-app && php artisan config:cache && php artisan optimize

      - name: Run Migrations ğŸ—‚ï¸
        run: cd laravel-app && php artisan migrate --env=testing --force

      # - name: Run Tests âœ…
      #   run: phpunit --testdox

      - name: Run Static Analysis ğŸ”
        run: phpstan analyse app/ --level=5
